# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-03 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='title',
            new_name='exception_args',
        ),
        migrations.RemoveField(
            model_name='main',
            name='code',
        ),
        migrations.RemoveField(
            model_name='main',
            name='language',
        ),
        migrations.RemoveField(
            model_name='main',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='main',
            name='style',
        ),
        migrations.AddField(
            model_name='main',
            name='exception_repr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='exception_string',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='exception_traceback',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='main',
            name='exception_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
